#!/usr/bin/env bash
# Bootstrap verification: ensure required workflow layer paths exist.
# Run after cloning or restoring a workspace.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MISSING=0

echo "==> Bootstrap: verifying workflow layer at $ROOT"

# ── Memory convention detection ──────────────────────────────────────
# Projects may use memory_bank/ (underscore, framework default) or
# memory-bank/ (hyphen, legacy project convention). Detect and persist.

MEMORY_DIR="memory_bank"  # framework default

HAS_HYPHEN=false
HAS_UNDERSCORE=false
[ -d "$ROOT/memory-bank" ] && HAS_HYPHEN=true
[ -d "$ROOT/memory_bank" ] && HAS_UNDERSCORE=true

if $HAS_HYPHEN && ! $HAS_UNDERSCORE; then
  MEMORY_DIR="memory-bank"
  echo "  DETECTED: memory-bank/ (hyphen convention)"
elif $HAS_UNDERSCORE && ! $HAS_HYPHEN; then
  echo "  Using: memory_bank/ (underscore convention)"
elif $HAS_HYPHEN && $HAS_UNDERSCORE; then
  # Both exist — prefer the one with project content files
  if [ -f "$ROOT/memory-bank/activeContext.md" ] || [ -f "$ROOT/memory-bank/productContext.md" ]; then
    MEMORY_DIR="memory-bank"
    echo "  DETECTED: both exist. Using memory-bank/ (has project content)."
  else
    echo "  Both exist. Using memory_bank/ (framework default)."
  fi
else
  echo "  Creating: memory_bank/ (framework default)"
  mkdir -p "$ROOT/memory_bank/snapshots"
fi

# Persist convention for agents
mkdir -p "$ROOT/.agent"
cat > "$ROOT/.agent/project-config.md" << PROJECTCONFIG
# Project Configuration

> Auto-generated by bootstrap.sh. Do not edit manually.

- **MEMORY_DIR:** \`$MEMORY_DIR\`
PROJECTCONFIG

# ── Core workflow layer ──────────────────────────────────────────────

for path in \
  ".gitignore" \
  ".agent/ROSTER.md" \
  ".agent/workflows/sdd-protocol.md" \
  ".agent/skills/README.md" \
  ".claude/agent-memory/solution-architect/MEMORY.md" \
  ".claude/agent-memory/verifier/MEMORY.md" \
  ".claude/skills/README.md" \
  ".codex/write-gate.md" \
  "docs/plans/README.md" \
  "docs/specs/README.md" \
  "docs/tasklist/README.md" \
  "docs/reports/README.md" \
  "$MEMORY_DIR/context.md" \
  "$MEMORY_DIR/progress.md" \
  "$MEMORY_DIR/decisions.md" \
  "$MEMORY_DIR/orchestrator-log.md" \
  "$MEMORY_DIR/review-log.md" \
  "$MEMORY_DIR/snapshots/.gitkeep"; do
  if [ ! -f "$ROOT/$path" ]; then
    echo "  MISSING: $path"
    MISSING=1
  else
    echo "  OK: $path"
  fi
done

if [ "$MISSING" -eq 1 ]; then
  echo "==> Workflow layer incomplete — review missing files above."
  exit 1
fi

echo "==> Workflow layer: OK"

# ── Dev environment checks (warnings only) ──────────────────────────

echo ""
echo "==> Dev environment checks..."

if [ -d "$ROOT/node_modules" ]; then
  echo "  OK: node_modules/"
else
  echo "  WARN: node_modules/ missing — run 'npm install'"
fi

if [ -n "${DATABASE_URL:-}" ]; then
  echo "  OK: DATABASE_URL is set"
elif [ -f "$ROOT/.env" ] && grep -q "DATABASE_URL" "$ROOT/.env" 2>/dev/null; then
  echo "  OK: DATABASE_URL found in .env"
else
  echo "  WARN: DATABASE_URL not set — builds may fail"
fi

echo "==> Dev environment checks done"
